version: '2'

services:
  app:
    build: ./app
    container_name: "Flask_App"
    links:
      - db
    env_file:
      - '.env'
    ports:
      - '8000:5000'

  db:
    image: mysql:5.7
    container_name:"MySQL_Database"
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: insta_admin
      MYSQL_PASSWORD: insta2018
      MYSQL_DATABASE: insta_db

